project:
  type: website

website:
  title: "Hariz Harisun"
  navbar:
    background: "#f4f1ea"
    foreground: "#382110"
    search: true
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog.qmd
        text: Blog
      - href: Project.qmd
        text: Projects
    right:
      - icon: github
        href: https://github.com/hariz-harisun
      - icon: facebook
        href: https://www.facebook.com/hariz.harisun
      - icon: linkedin
        href: https://www.linkedin.com/in/harizhazril/
      - icon: rss
        href: index.xml
format:
  html:
    theme: cosmo
    backgroundcolor: "#f9f7f4"
    css: styles.css
    toc: true
