project:
  type: website

website:
  title: "Hariz-Harisun.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - favorites.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



