project:
  type: website

website:
  title: "Hariz-Harisun.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog.qmd
        text: Blog
      - href: Project.qmd
        text: Project
    right:
      - icon: github
        href: https://github.com/hariz-harisun
      - icon: facebook
        href: https://www.facebook.com/hariz.harisun
      - icon: linkedin
        href: https://www.linkedin.com/in/harizhazril/
      - icon: rss
        href: index.xml
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



