---
draft: false
title: "The reason I shall not give up"
subtitle: "[No. 001]"
date: "2025-04-14"
time: current
categories: ["Jurnal Teroka-matik"]
image: ""
authors: ["M. Hariz Hazril"]
---

### No. 001

I was good at math in primary school. It’s a damn easy concept you can grasp. Struggled a bit as it went to middle school. Then, Addmath crashed into my life. With the strong stereotype that Addmath was hard as heck, it became the belief of most students, including me. My SPM result for this subject was not great. I couldn’t solve many questions. So, I left them blank without even trying. That’s where I never tried to learn or understand it.

Now, I’m an undergraduate in Pure Physics with a minor in Computer Science. Both subjects demand a high-level understanding of mathematics. And yet, I’m still bad at math. Especially subjects that lean hard into it (Quantum Physics, etc., bla bla bla). It’s funny how I still want to pursue this area. You can’t become a scientist or researcher if you’re bad at math. Causality. Really. It’s like you’re doing something you don’t truly understand. Just guessing. Tikam something.

My lecturer also rejected me for his Final Year Project supervision because I’m awful at Quantum Mechanics. Can’t blame him as it really brought big problems for me in the end. But still, my bravery was there for trying to apply.

Although I’m really struggling with math, I’m grateful that the fire still burns through the ashes. I always find motivation to start studying math. But executing it? That’s a whole other level.

When I see my older brother struggle with math (which feels easy to me), it reminds me of myself. That I shouldn’t give up on learning it. The point isn’t how many you get right or wrong. It’s about how long you keep going.

Consistency (istiqāmah) is the crucial, golden key to learning anything.

This is my journey with math.
Once called a killer, it’s just part of my liver now.

— hh (10:54 PM, 14/04/2025)


